# Generated by Django 2.1.3 on 2019-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtlrmodel',
            name='rtlrdistrict',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rtlrmodel',
            name='rtlrpincode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='rtlrmodel',
            name='rtlrstate',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
