# Generated by Django 2.1.3 on 2019-02-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190210_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtlrmodel',
            name='rtlrpcolony',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
