# Generated by Django 2.1.3 on 2019-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='auid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
