# Generated by Django 2.1.3 on 2019-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0003_auto_20190210_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='asphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
