# Generated by Django 2.1.3 on 2019-02-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0004_all_asphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='asphoto',
        ),
    ]
